  config:
    target: "http://localhost:3030/"
    processor: "./wss-func/func.js"
    phases:
      - duration: 1000
        arrivalRate: 50
  scenarios:
    - flow:
        - function: "generateRandomData"
        - post:
            url: "http://localhost:3030/register"
            json:
              name: "{{ name }}"
            capture:
              json: "$.uuid"
              as: uuid
        - post:
            url: "http://localhost:3030/unregister"
            json:
              name: "{{ name }}"
              uuid: "{{ uuid }}"
